---
title: "Group by Time Effects"
author: "Kendra Wyant"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

### Set Up Environment


```{r, packages_workflow}
#| message: false
#| warning: false

# handle conflicts
options(conflicts.policy = "depends.ok")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_ml.R?raw=true")
tidymodels_conflictRules()
```


```{r, packages_script}
#| message: false
#| warning: false

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tidymodels))
suppressPackageStartupMessages(library(tidyposterior))
library(kableExtra, exclude = "group_rows")
library(Rcpp, exclude = "populate")
library(brms, exclude = c("ar", "mixture"))


theme_set(theme_classic()) 
```


```{r source_functions}
#| output: false

devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
# CHTC support functions
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/chtc/static_files/fun_chtc.R?raw=true")
```

```{r, absolute_paths}
path_processed <- format_path(str_c("studydata/risk/data_processed/lag"))
path_models_lag <- format_path(str_c("studydata/risk/models/lag"))
```


### Read in Model Performance Metrics

```{r}
auroc_dem_0 <- read_csv(here::here(path_models_lag, "test_auroc_dem_6_x_5_1week_0_v1_nested.csv"),
                      col_types = cols()) |> 
  mutate(fold_num = rep(1:10, 3),
         repeat_num = c(rep(1, 10), rep(2, 10), rep(3, 10))) |> 
  select(-outer_split_num)


auroc_dem_24 <- read_csv(here::here(path_models_lag, "test_auroc_dem_6_x_5_1week_24_v1_nested.csv"),
                      col_types = cols()) |> 
  mutate(fold_num = rep(1:10, 3),
         repeat_num = c(rep(1, 10), rep(2, 10), rep(3, 10))) |> 
  select(-outer_split_num)

auroc_dem_72 <- read_csv(here::here(path_models_lag, "test_auroc_dem_6_x_5_1week_72_v1_nested.csv"),
                      col_types = cols()) |> 
  mutate(fold_num = rep(1:10, 3),
         repeat_num = c(rep(1, 10), rep(2, 10), rep(3, 10))) |> 
  select(-outer_split_num)

auroc_dem_168 <- read_csv(here::here(path_models_lag, "test_auroc_dem_6_x_5_1week_168_v1_nested.csv"),
                      col_types = cols()) |> 
  mutate(fold_num = rep(1:10, 3),
         repeat_num = c(rep(1, 10), rep(2, 10), rep(3, 10))) |> 
  select(-outer_split_num)

auroc_dem_336 <- read_csv(here::here(path_models_lag, "test_auroc_dem_6_x_5_1week_336_v1_nested.csv"),
                      col_types = cols()) |> 
  mutate(fold_num = rep(1:10, 3),
         repeat_num = c(rep(1, 10), rep(2, 10), rep(3, 10))) |> 
  select(-outer_split_num)
```


```{r}
auroc_dem_all <- auroc_dem_0 |> 
  mutate(lag = 0) |> 
  bind_rows(auroc_dem_24 |> 
              mutate(lag = 24)) |>
  bind_rows(auroc_dem_72 |> 
              mutate(lag = 72)) |>
  bind_rows(auroc_dem_168 |> 
              mutate(lag = 168)) |>
  bind_rows(auroc_dem_336 |> 
              mutate(lag = 336))

set.seed(101)
```

### Race

```{r}
data <- auroc_dem_all |> 
  select(id = fold_num, id2 = repeat_num, `not white`, `non-hispanic white` = white, lag) |> 
  pivot_longer(cols = c(`not white`, `non-hispanic white`), names_to = "race", values_to = "auroc") |> 
  # mutate(race_c = if_else(race == "not white", -.5, .5),
  #        lag_c = lag - mean(lag)) |> 
  glimpse()

model_race <- brm(
  formula = auroc ~ 1 + race + lag + race*lag + (1 | id2/id), # folds nested in repeats
  data = data,
  family = gaussian(link = "logit"), # normal distribution w/auroc bounded between 0 and 1
  chains = 4,
  control = list(adapt_delta = 0.95), 
  iter = 6000,
  seed = 123
)

print(model_race)
```

```{r}
plot(model_race)
```


```{r}
bayesplot::mcmc_trace(model_race, pars = c("b_Intercept", "b_racenotwhite", "b_lag", "b_racenotwhite:lag"))

bayesplot::mcmc_acf(model_race, pars = c("b_Intercept", "b_racenotwhite", "b_lag", "b_racenotwhite:lag"))

bayesplot::mcmc_dens(model_race, pars = c("b_Intercept", "b_racenotwhite", "b_lag", "b_racenotwhite:lag"))
```

### Sex
```{r}
data <- auroc_dem_all |> 
  select(id = fold_num, id2 = repeat_num, female, male, lag) |> 
  pivot_longer(cols = c(female, male), names_to = "sex", values_to = "auroc") |>
  mutate(sex = factor(sex)) |>
  glimpse()

model_sex <- brm(
  formula = auroc ~ 1 + sex + lag + sex*lag + (1 | id2/id), # folds nested in repeats 
  data = data,
  family = gaussian(link = "logit"), # normal distribution w/auroc bounded between 0 and 1
  chains = 4,
  iter = 6000,
  seed = 123
)

summary(model_sex)
```

```{r}
bayesplot::mcmc_trace(model_sex, pars = c("b_Intercept", "b_sexmale", "b_lag", "b_sexmale:lag"))

bayesplot::mcmc_acf(model_sex, pars = c("b_Intercept", "b_sexmale", "b_lag", "b_sexmale:lag"))

bayesplot::mcmc_dens(model_sex, pars = c("b_Intercept", "b_sexmale", "b_lag", "b_sexmale:lag"))
```

### Income
```{r}
data <- auroc_dem_all |> 
  select(id = fold_num, id2 = repeat_num, `above poverty`, `below poverty`, lag) |> 
  pivot_longer(cols = c(`above poverty`, `below poverty`), names_to = "income", 
               values_to = "auroc") |>
  mutate(income = factor(income)) |>
  glimpse()

model_income <- brm(
  formula = auroc ~ 1 + income + lag + income*lag + (1 | id2/id), # folds nested in repeats
  data = data,
  family = gaussian(link = "logit"), # normal distribution w/auroc bounded between 0 and 1
  chains = 4,
  iter = 6000,
  seed = 123
)

summary(model_income)
```

```{r}
bayesplot::mcmc_trace(model_race, pars = c("b_Intercept", "b_incomeabovepoverty", "b_lag", "b_incomeabovepoverty:lag"))

bayesplot::mcmc_acf(model_race, pars = c("b_Intercept", "b_incomeabovepoverty", "b_lag", "b_incomeabovepoverty:lag"))

bayesplot::mcmc_dens(model_race, pars = c("b_Intercept", "b_incomeabovepoverty", "b_lag", "b_incomeabovepoverty:lag"))
```